version: "3.6"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: docker-entrypoint
  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    env_file:
      - config/dev.env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  migrate:
    build: .
    command: docker-migrate
volumes:
    postgres: