"""Create Machine and Print_History models

Revision ID: 6f54b7fbb707
Revises: 
Create Date: 2022-05-04 11:13:14.101190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f54b7fbb707'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_number', sa.Integer(), nullable=True),
    sa.Column('mqtt_instance', sa.String(), nullable=True),
    sa.Column('platform_type', sa.String(), nullable=True),
    sa.Column('customer', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_number'),
    sa.UniqueConstraint('mqtt_instance')
    )
    op.create_table('print_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.String(length=255), nullable=True),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('file_name', sa.Text(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('print_duration', sa.Integer(), nullable=True),
    sa.Column('total_duration', sa.Integer(), nullable=True),
    sa.Column('slicer_estimated_time', sa.Integer(), nullable=True),
    sa.Column('filament_used', sa.Integer(), nullable=True),
    sa.Column('slicer', sa.Text(), nullable=True),
    sa.Column('material', sa.Text(), nullable=True),
    sa.Column('nozzle_diameter', sa.Text(), nullable=True),
    sa.Column('first_layer_height', sa.Text(), nullable=True),
    sa.Column('first_layer_bed_temp', sa.Text(), nullable=True),
    sa.Column('object_height', sa.Integer(), nullable=True),
    sa.Column('print_metadata', sa.JSON(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('print_history')
    op.drop_table('machine')
    # ### end Alembic commands ###
